CREATE TABLE IF NOT EXISTS platforms (
  platform_id TEXT PRIMARY KEY,
  platform_name TEXT NOT NULL,
  platform_type TEXT NOT NULL DEFAULT 'generic',
  platform_url TEXT,
  platform_domain TEXT,
  environment TEXT,
  app_version TEXT,
  sdk_name TEXT,
  sdk_version TEXT,
  source TEXT,
  first_seen TEXT NOT NULL,
  last_seen TEXT NOT NULL,
  total_events INTEGER NOT NULL DEFAULT 0,
  total_pageviews INTEGER NOT NULL DEFAULT 0,
  total_sessions INTEGER NOT NULL DEFAULT 0,
  total_visitors INTEGER NOT NULL DEFAULT 0,
  last_ip TEXT,
  last_ip_hash TEXT,
  last_platform_ip TEXT,
  last_country TEXT,
  last_region TEXT,
  last_city TEXT,
  last_event_id TEXT,
  last_event_type TEXT,
  api_key_hash TEXT,
  api_key_updated_at TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  capabilities_json TEXT NOT NULL DEFAULT '{}'
);
