CREATE TABLE IF NOT EXISTS platform_visitors (
  platform_id TEXT NOT NULL,
  visitor_id TEXT NOT NULL,
  user_id TEXT,
  anonymous_id TEXT,
  first_seen TEXT NOT NULL,
  last_seen TEXT NOT NULL,
  last_ip TEXT,
  last_ip_hash TEXT,
  country TEXT,
  region TEXT,
  region_code TEXT,
  city TEXT,
  continent TEXT,
  colo TEXT,
  asn INTEGER,
  as_organization TEXT,
  latitude TEXT,
  longitude TEXT,
  postal_code TEXT,
  timezone TEXT,
  language TEXT,
  user_agent TEXT,
  browser TEXT,
  browser_version TEXT,
  os TEXT,
  os_version TEXT,
  device TEXT,
  device_vendor TEXT,
  device_model TEXT,
  screen_width INTEGER,
  screen_height INTEGER,
  viewport_width INTEGER,
  viewport_height INTEGER,
  device_pixel_ratio REAL,
  color_depth INTEGER,
  last_page_url TEXT,
  last_path TEXT,
  last_referrer TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}', PRIMARY KEY(platform_id, visitor_id)
);
