CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  received_at TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_version TEXT,
  platform_id TEXT NOT NULL,
  platform_name TEXT NOT NULL,
  platform_type TEXT NOT NULL DEFAULT 'generic',
  environment TEXT,
  app_version TEXT,
  sdk_name TEXT,
  sdk_version TEXT,
  source TEXT,
  user_id TEXT,
  session_id TEXT NOT NULL,
  visitor_id TEXT NOT NULL,
  anonymous_id TEXT,
  trace_id TEXT,
  request_id TEXT,
  page_url TEXT,
  path TEXT,
  query_string TEXT,
  title TEXT,
  referrer TEXT,
  referrer_host TEXT,
  language TEXT,
  accept_language TEXT,
  timezone TEXT,
  country TEXT,
  region TEXT,
  region_code TEXT,
  city TEXT,
  continent TEXT,
  colo TEXT,
  asn INTEGER,
  as_organization TEXT,
  latitude TEXT,
  longitude TEXT,
  postal_code TEXT,
  metro_code TEXT,
  ip TEXT,
  ip_hash TEXT,
  platform_ip TEXT,
  forwarded_for TEXT,
  ip_source TEXT,
  user_agent TEXT,
  browser TEXT,
  browser_version TEXT,
  os TEXT,
  os_version TEXT,
  device TEXT,
  device_vendor TEXT,
  device_model TEXT,
  screen_width INTEGER,
  screen_height INTEGER,
  viewport_width INTEGER,
  viewport_height INTEGER,
  device_pixel_ratio REAL,
  color_depth INTEGER,
  connection_type TEXT,
  connection_downlink REAL,
  connection_rtt INTEGER,
  connection_save_data INTEGER NOT NULL DEFAULT 0,
  http_method TEXT,
  request_url TEXT,
  request_scheme TEXT,
  request_host TEXT,
  request_path TEXT,
  request_query TEXT,
  request_content_type TEXT,
  request_content_length INTEGER,
  accept_header TEXT,
  accept_encoding TEXT,
  origin_header TEXT,
  cf_ray TEXT,
  tls_version TEXT,
  client_tcp_rtt INTEGER,
  client_quic_rtt INTEGER,
  bot_score INTEGER,
  verified_bot INTEGER NOT NULL DEFAULT 0,
  ja3 TEXT,
  ja4 TEXT,
  response_status INTEGER,
  duration_ms INTEGER NOT NULL DEFAULT 0,
  max_scroll INTEGER NOT NULL DEFAULT 0,
  clicks INTEGER NOT NULL DEFAULT 0,
  outbound_clicks INTEGER NOT NULL DEFAULT 0,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  data_json TEXT NOT NULL DEFAULT '{}',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  headers_json TEXT NOT NULL DEFAULT '{}',
  cf_json TEXT NOT NULL DEFAULT '{}',
  request_json TEXT NOT NULL DEFAULT '{}',
  payload_json TEXT NOT NULL DEFAULT '{}',
  raw_event_json TEXT NOT NULL DEFAULT '{}'
);
