name = "github-page-insights-worker"
main = "src/index.js"
compatibility_date = "2026-09-10"
workers_dev = true

[vars]
GITHUB_OWNER = "mehrdadmb2"
GITHUB_REPO = "github-page-insights"
GITHUB_BRANCH = "main"

[[d1_databases]]
binding = "DB"
database_name = "github-page-insights"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
